### PR TITLE
Fixed bingo get fails on Windows

### LINKED ISSUE #127: bingo get fails on Windows: bingo.tmp.mod is being used by another process
**`bingo version` output**:
`v0.7`

**`go version` output**:
`go version go1.19.3 windows/amd64`

**What happened**:
```sh
bingo get
Error: get command failed: get: 0: getting github.com\bwplotka\bingo@v0.5.1: rename mod file: rename C:\Users\jayan\scoop\apps\go\current\src\gitlab.wikimedia.org\repos\releng\cli\.bingo\bingo.tmp.mod C:\Users\jayan\scoop\apps\go\current\src\gitlab.wikimedia.org\repos\releng\cli\.bingo\bingo.mod: The process cannot access the file because it is being used by another process.
```
**What you expected to happen**:
It installs the dependencies

**How to reproduce it (as minimally and precisely as possible)**:
Run `bingo get` on Windows.

**Logs (use `bingo get -v <thing you do>` for verbose output)**:

```
bingo get -v
getting target github.com\bwplotka\bingo@v0.5.1 (module github.com/bwplotka/bingo )
exec 'go list -modfile=C:\Users\jayan\scoop\apps\go\current\src\gitlab.wikimedia.org\repos\releng\cli\.bingo\bingo.tmp.mod -mod=mod -f={{.Name}} github.com\bwplotka\bingo'
exec 'go build -modfile=C:\Users\jayan\scoop\apps\go\current\src\gitlab.wikimedia.org\repos\releng\cli\.bingo\bingo.tmp.mod -o=bingo-v0.5.1 github.com\bwplotka\bingo'
Error: get command failed
> main.main     C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/main.go:223
> runtime.main  C:/Users/jayan/scoop/apps/go/current/src/runtime/proc.go:250
> runtime.goexit        C:/Users/jayan/scoop/apps/go/current/src/runtime/asm_amd64.s:1594
get
> main.main.func2       C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/main.go:147
> main.main.func5       C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/main.go:215
> github.com/oklog/run.(*Group).Run.func1       C:/Users/jayan/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38
> runtime.goexit        C:/Users/jayan/scoop/apps/go/current/src/runtime/asm_amd64.s:1594
0: getting github.com\bwplotka\bingo@v0.5.1
> main.getAll   C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/get.go:119
> main.get      C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/get.go:154
> main.main.func2       C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/main.go:146
> main.main.func5       C:/Users/jayan/go/pkg/mod/github.com/bwplotka/bingo@v0.7.0/main.go:215
> github.com/oklog/run.(*Group).Run.func1       C:/Users/jayan/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38
> runtime.goexit        C:/Users/jayan/scoop/apps/go/current/src/runtime/asm_amd64.s:1594
rename mod file: rename C:\Users\jayan\scoop\apps\go\current\src\gitlab.wikimedia.org\repos\releng\cli\.bingo\bingo.tmp.mod C:\Users\jayan\scoop\apps\go\current\src\gitlab.wikimedia.org\repos\releng\cli\.bingo\bingo.mod: The process cannot access the file because it is being used by another process.
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by melvinmurvie**
This PR is to make sure opened files are closed immediately (instead of at defer) if we don't need it anymore.

On Windows an error occurs when we try to rename from/to an opened files. Calling `os.Rename(old, new)` we should make sure to close both `old` and `new` files (if `new` is existed and opened).

Fixes #127

### CODE REVIEW

File: get.go [hunk 1]
```diff
@@ -200,7 +200,9 @@ func get(ctx context.Context, logger *log.Logger, c getConfig, rawTarget string)
 			if err != nil {
 				return errors.Wrapf(err, "found unparsable mod file %v. Uninstall it first via get %v@none or fix it manually.", e, name)
 			}
-			defer errcapture.Do(&err, mf.Close, "close")
+			if err := mf.Close(); err != nil {
```
Comment (bwplotka) [inline get.go:203]: Thanks! Can we ensure we don't use `mf` variable after Close? Here we can do easily with `dpkg := *mf.DirectPackage()` and then close and then append to target (:

File: get.go [hunk 2]
```diff
@@ -260,7 +262,9 @@ func get(ctx context.Context, logger *log.Logger, c getConfig, rawTarget string)
...
```
Comment (bwplotka) [inline get.go:265]: ditto. We can't use `mf` after Close even if by accident in this code we can.

File: get.go [hunk 3]
```diff
@@ -652,6 +663,12 @@ func getPackage(ctx context.Context, logger *log.Logger, c installPackageConfig,
 		return err
 	}
 
+	// We have close it once here so the defer func does not need to close it again.
+	closed = true
+	if err := tmpModFile.Close(); err != nil {
```
Comment (bwplotka) [inline get.go:668]: Same here, it's not acceptable to use `tmpModFile` var that is closed. It might work by accident now, but will cause surprises later on.

Why not closing right before `os.Rename` (and saving tmpModFile fileapath to variable?)

**Review by bwplotka — CHANGES_REQUESTED** [review]
Thanks so much for helping!

I gave some suggestions on a bit cleaner approach, but good progress and thanks for approaching this! 💪🏽

**Comment by melvinmurvie** [comment]
> Thanks so much for helping!
> 
> I gave some suggestions on a bit cleaner approach, but good progress and thanks for approaching this! 💪🏽

@bwplotka Thanks for the suggestions! I've already made the changes, please take a look and let me know if there's anything else need to improve! 🙏🏽

**Review by bwplotka — APPROVED** [review]
Thanks!
